apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.deployment.db.name }} 
  namespace: apps
spec:
  selector:
    matchLabels:
      app: postgres  
  replicas: {{ .Values.deployment.db.replicas }}
  template:
    metadata:
      labels:
        app: postgres  
    spec:
      containers:
        - name: {{ .Values.deployment.backend.containers.name }} 
          image:  "{{ .Values.deployment.db.containers.image }}:{{ .Values.deployment.db.containers.tag }}"
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: todos
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          volumeMounts:
          - name: mendix-pgdata
            mountPath: "/var/lib/postgresql/data"
              
      volumes:
        - name: mendix-pgdata
          hostPath:
            path: "/home/houssine/workspace/Todo-gitlab/data"
            type: DirectoryOrCreate




















