apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.Deployment.backend.name }} #backend-deployment
  namespace: apps
  labels:
    app: noteapp-backend
spec:
  replicas: {{ .Values.Deployment.backend.replicas }} #1
  selector:
    matchLabels:
      app:  {{ .Values.Deployment.backend.labels.app }}  #noteapp-backend
  template:
    metadata:
      labels:
        app: {{ .Values.Deployment.backend.labels.app }}  #noteapp-backend
    spec:
      containers:
      - name: {{ .Values.Deployment.backend.containers.name }}  #noteapp-backend
        image: "{{ .Values.Deployment.backend.containers.image }}:{{ .Values.Deployment.backend.containers.tag }}" #houssinedahmane/todo_app_with_k8s_backend:1.0.024
        ports:
        - name: http-web
          containerPort: 3001
        env:
        - name: DB_PORT
          value: "5432"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_DATABASE
          value: todos
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password #{{ .Values.database.password }}

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: apps
  labels:
    app: noteapp-backend
spec:
  type: NodePort
  selector:
    app: noteapp-backend
  ports:
    - protocol: TCP
      port: 3001
      nodePort: 30001
      targetPort: 3001