apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: apps
  labels:
    app: noteapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noteapp-backend
  template:
    metadata:
      labels:
        app: noteapp-backend
    spec:
      containers:
      - name: noteapp-backend
        image: registry.gitlab.com/houssinedahmane/todo_app_with_k8s/noteapp-backend-1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: DB_PORT
          value: "5432"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_DATABASE
          value: todos
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password #{{ .Values.database.password }}

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: apps
  labels:
    app: noteapp-backend
spec:
  type: NodePort
  selector:
    app: noteapp-backend
  ports:
    - protocol: TCP
      port: 3001
      nodePort: 30001
      targetPort: 3001