apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.frontend.name }}
  namespace: apps
  labels:
    app: noteapp-frontend
spec:
  replicas: {{ .Values.deployment.frontend.replicas }}
  selector:
    matchLabels:
      app: noteapp-frontend
  template:
    metadata:
      labels:
        app: noteapp-frontend
    spec:
      containers:
      - name: {{ .Values.deployment.frontend.containers.name }} #noteapp-frontend
        image: "{{ .Values.deployment.frontend.containers.image }}:{{ .Values.deployment.frontend.containers.tag }}" # houssinedahmane/todo_app_with_k8s_frontend:1.0.024
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://192.168.49.2:30001/api

