apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Deployment.backend.name }}
  namespace: apps
  labels:
    app: noteapp-backend
spec:
  replicas: {{ .Values.Deployment.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Deployment.backend.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.Deployment.backend.labels.app }}
    spec:
      containers:
      - name: {{ .Values.Deployment.backend.containers.name }}
        image: "{{ .Values.Deployment.backend.containers.image }}:{{ .Values.Deployment.backend.containers.tag }}"
        ports:
        - name: http-web
          containerPort: 3001
        env:
        - name: DB_PORT
          value: "5432"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_DATABASE
          value: todos
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password 