---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.db.name }} 
  namespace: apps
spec:
  type: {{ .Values.services.db.type }} 
  ports:
    - port: {{ .Values.services.db.port }} 
  selector:
    app: postgres

