---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.frontend.name }}
  namespace: apps
  labels:
    app: noteapp-frontend
spec:
  selector:
    app: noteapp-frontend
  ports:
  - protocol: "TCP"
    port: {{ .Values.services.backend.port }}
    targetPort: {{ .Values.services.backend.targetPort }}
  type: {{ .Values.services.backend.type }}
