---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: apps
  labels:
    app: noteapp-frontend
spec:
  selector:
    app: noteapp-frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer
