---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: apps
  labels:
    app: noteapp-frontend
spec:
  type: NodePort
  selector:
    app: noteapp-frontend
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30002
      targetPort: 3000