---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.backend.name }} 
  namespace: apps
  labels:
    app: noteapp-backend
spec:
  type: {{ .Values.services.backend.type }}
  selector:
    app: noteapp-backend
  ports:
    - protocol: TCP
      port: {{ .Values.services.backend.port }}
      nodePort: {{ .Values.services.backend.nodePort }}
      targetPort: {{ .Values.services.backend.targetPort }}