---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: apps
  labels:
    app: noteapp-backend
spec:
  type: NodePort
  selector:
    app: noteapp-backend
  ports:
    - protocol: TCP
      port: 3001
      nodePort: 30001
      targetPort: 3001